name: PR Push check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: pnpm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint:code

  type:
    name: Type
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Type
        run: pnpm run lint:type
